// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopbridge_base.Data;

namespace Shopbridge_base.Migrations
{
    [DbContext(typeof(Shopbridge_Context))]
    partial class Shopbridge_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shopbridge_base.Domain.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Electronics",
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Mobile",
                            CategoryName = "Mobile"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Furniture",
                            CategoryName = "Furniture"
                        });
                });

            modelBuilder.Entity("Shopbridge_base.Domain.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_Id = 1,
                            CategoryId = 1,
                            Price = 12.0,
                            ProductDescription = "TV",
                            ProductName = "LG 21 LED",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 8,
                            CategoryId = 1,
                            Price = 12.0,
                            ProductDescription = "TV",
                            ProductName = "Samsun 55 LED",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 9,
                            CategoryId = 1,
                            Price = 12.0,
                            ProductDescription = "TV",
                            ProductName = "samsung 81 LED",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 2,
                            CategoryId = 2,
                            Price = 12.0,
                            ProductDescription = "Mobile",
                            ProductName = "Samsung s21",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 4,
                            CategoryId = 2,
                            Price = 12.0,
                            ProductDescription = "Mobile",
                            ProductName = "Samsung A50",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 5,
                            CategoryId = 2,
                            Price = 12.0,
                            ProductDescription = "Mobile",
                            ProductName = "Nokia n80",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 6,
                            CategoryId = 2,
                            Price = 12.0,
                            ProductDescription = "Mobile",
                            ProductName = "Nokia s02",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 7,
                            CategoryId = 2,
                            Price = 12.0,
                            ProductDescription = "Mobile",
                            ProductName = "oppo s21",
                            Quantity = 2
                        },
                        new
                        {
                            Product_Id = 3,
                            CategoryId = 3,
                            Price = 12.0,
                            ProductDescription = "Table",
                            ProductName = "Table 4x8",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Shopbridge_base.Domain.Models.Product", b =>
                {
                    b.HasOne("Shopbridge_base.Domain.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
